#!/bin/bash

echo "🚀 CaseQuest Phase 1 Deployment - 10% Rollout"
echo "=============================================="

# Step 1: Deploy built application
echo "📦 Deploying application..."
firebase deploy --only hosting

if [ $? -ne 0 ]; then
    echo "❌ Deployment failed. Aborting."
    exit 1
fi

echo "✅ Application deployed successfully"

# Step 2: Instructions for Firebase Console setup
echo ""
echo "🔧 NEXT STEPS - Complete in Firebase Console:"
echo "=============================================="
echo ""
echo "1. Remote Config Setup:"
echo "   - Go to Firebase Console → Remote Config"
echo "   - Import parameters from firebase-remote-config-setup.json"
echo "   - Set ux_rollout_percentage = 10"
echo "   - Set all ux_*_enabled flags = true"
echo "   - PUBLISH changes"
echo ""
echo "2. A/B Testing Setup:"
echo "   - Go to Firebase Console → A/B Testing"
echo "   - Create 'Endowed Progress' experiment:"
echo "     * Parameter: endowed_progress_percent"
echo "     * Variants: 0%, 10%, 25%"
echo "     * Target: 10% of new users"
echo "     * Goal: first_lesson_complete"
echo "   - Create 'Next Action Policy' experiment:"
echo "     * Parameter: next_action_policy"
echo "     * Variants: weakness_first, time_budget_first"
echo "     * Target: existing users with >3 lessons"
echo "     * Goal: next_action_taken"
echo ""
echo "3. GA4 Monitoring:"
echo "   - Set up cohort analysis dashboard"
echo "   - Configure rollback alerts"
echo "   - Monitor for 24 hours before ramp-up"
echo ""
echo "🎯 SUCCESS CRITERIA (24 hours):"
echo "- Onboarding completion >80% (baseline: 70%)"
echo "- First lesson conversion >60% (baseline: 50%)"
echo "- Day 1 retention >40% (baseline: 35%)"
echo "- No error rate increase >1%"
echo ""
echo "⚠️  ROLLBACK TRIGGERS:"
echo "- Any primary KPI drops >10% vs baseline"
echo "- Error rate increases >2%"
echo "- User complaints about UI issues"
echo ""
echo "🔄 ROLLBACK PROCEDURE:"
echo "1. Firebase Console → Remote Config"
echo "2. Set ux_rollout_percentage = 0"
echo "3. Publish immediately"
echo "4. Monitor recovery for 30 minutes"
echo ""
echo "📊 Monitoring Dashboard: https://analytics.google.com/analytics/web/"
echo "🔧 Remote Config: https://console.firebase.google.com/project/casequest-62b9b/config"
echo "🧪 A/B Testing: https://console.firebase.google.com/project/casequest-62b9b/abtesting"
echo ""
echo "✅ Phase 1 deployment ready for activation!"
echo "   Next: Enable flags in Firebase Console and monitor for 24h"
